#!/bin/bash

# Configuration
# Read key from environment variable (set by Docker/Coolify)
KEY="${YOUTUBE_STREAM_KEY:-YOUR_KEY_HERE}"
RTMP_URL="rtmp://a.rtmp.youtube.com/live2/$KEY"
PLAYLIST="/app/videos/playlist.txt"

echo "📡 [INGEST] Forever-Streamer Engine Initialized."

while true; do
  # Verify playlist exists before starting
  if [ ! -f "$PLAYLIST" ]; then
    echo "⏳ [INGEST] Waiting for playlist.txt to be generated by switcher..."
    sleep 5
    continue
  fi

  echo "🎥 [INGEST] $(date) | Starting FFmpeg Ingest..."
  
  # THE INDESTRUCTIBLE COMMAND (STRICT CBR)
  ffmpeg -y -re -f concat -safe 0 -stream_loop -1 -i "$PLAYLIST" \
    -c:v libx264 -preset ultrafast -tune zerolatency \
    -b:v 2500k -minrate 2500k -maxrate 2500k -bufsize 5000k \
    -nal-hrd cbr -pix_fmt yuv420p -g 50 \
    -c:a aac -b:a 128k -ar 44100 \
    -f flv "$RTMP_URL"

  echo "⚠️ [INGEST] $(date) | FFmpeg process exited unexpectedly."
  echo "🚀 [INGEST] Restarting engine in 5 seconds..."
  sleep 5
done
